# Let travis know the language it needs to run
language: python

# Mention the python version in which travis will run the app
python:
  - "3.6"
  
# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
install:
  - pip install -r requirements.txt
  
script: true
  - nosetests --with-coverage --coverage report
  
 # Another command/method to run tests
script: 
  - python TestCalculator.py

deploy:
  provider: heroku
  api_key:
    secure:  $HEROKU_API_KEY
  app: lab3practice
  on:
    repo: amity871028/lab3practice
    
