# Let travis know the language it needs to run
language: python

# Mention the python version in which travis will run the app
python:
  - "3.6"
  
# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
script: true
  - nosetests --with-coverage --coverage report
  
 # Another command/method to run tests
script: 
  - python TestCalculator.py

deploy:
  provider: heroku
  api_key:
    secure: 4d4f0194-d395-4c76-b618-61c8269f86f9
  app: test-my-travisci-project
  on:
    repo: amity871028/lab3practice
    
